substitutions:
  name: "Living Room"  ## Location & Entity Names (Capitals and Spaces Allowed)

esphome:
  name: "air-quality-living-room" # Set the name to be shown in ESPHome
  min_version: 2024.11.0 # Optional. Update or comment out if needed.
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid # Pulls from ESPHome secrets
  password: !secret wifi_password # Pulls from ESPHome secrets

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome

# Enable logging
logger:
  logs:
    sensor: none
    binary_sensor: none
    homeassistant.binary_sensor: none
    pm1006: none
    ens160_i2c: none
    bme280_i2c: none

## Serial Port for the IKEA Sensor
uart:
  - rx_pin: 13
    baud_rate: 9600

i2c:
  ## I²C Port - For Temp/Humidity/Pressure & CO²/VOC Sensors
  sda: 4
  scl: 5
  scan: true
  id: bus_a

binary_sensor:
  ## Use the on-board LED to show "Fan Running"
  - platform: gpio
    name: $name Fan
    id: fan
    pin:
      number: D4
      # D4
      inverted: true

  ## Brightness Sensor for HA Automations
  - platform: template
    name: $name Lights
    id: bright

sensor:
  ## IKEA PMS 2.5um Sensor
  - platform: pm1006
    id: aq_sensor
    pm_2_5:
      name: $name 2.5µm Concentration
      accuracy_decimals: 1

  ## CO²/VOC Sensor
  - platform: ens160_i2c
    eco2:
      name: $name CO²
      accuracy_decimals: 0
    tvoc:
      name: $name T-VOC
      accuracy_decimals: 0
    aqi:
      name: $name Air Quality Index
      id: ens160_air_quality_index
    address: 0x53
    update_interval: 10s
    compensation:
      temperature: bme_temp
      humidity: bme_humi
    ## After Calibration, Uncomment and change "baseline:"
    # baseline: 0x4AB7

  ## Temp/Humidity/Pressure Sensor
  - platform: bme280_i2c
    temperature:
      name: $name Temperature
      id: bme_temp
      oversampling: 4x
    humidity:
      name: $name Humidity
      id: bme_humi
      oversampling: 4x
    pressure:
      name:  $name Pressure
      id: bme_press
      oversampling: 4x
    iir_filter: 16x
    address: 0x76
    update_interval: 10s

  ## The IKEA Light Level Sensor
  # Comment out this whole section if ommitting the 10K ohm resistor to the light sensor
  - platform: adc
    id: light_sensor
    pin: A0
    update_interval: 1s
    ## Check the value and turn On/Off our Binary Sensor
    on_value:
      - lambda: !lambda |
          if (x > 0.01) {
            id(bright).publish_state(true);
            } else {
              id(bright).publish_state(false);
              }

text_sensor:
  - platform: template
    name: $name Air Quality Rating
    lambda: |-
      switch ( (int) (id(ens160_air_quality_index).state) ) {
        case 1: return {"Excellent"};
        case 2: return {"Good"};
        case 3: return {"Moderate"};
        case 4: return {"Poor"};
        case 5: return {"Unhealthy"};
        default: return {"Not Available"};
      }
